sudo: required
services:
  - docker

before_install:
  - docker build -t rmaznytsia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rmaznytsia/react-test npm test -- --coverage

after_success:
  - docker build -t rmaznytsia/multi-client ./client
  - docker build -t rmaznytsia/multi-worker ./worker
  - docker build -t rmaznytsia/multi-server ./server
  - docker build -t rmaznytsia/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push rmaznytsia/multi-client  
  - docker push rmaznytsia/multi-worker
  - docker push rmaznytsia/multi-server
  - docker push rmaznytsia/multi-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-eu-west-2-564461623336
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



  
 